
CREATE TABLE wilayas (
id BIGSERIAL PRIMARY KEY,
code VARCHAR(5) NOT NULL UNIQUE,
name_ar VARCHAR(100) NOT NULL,
name_fr VARCHAR(100) NOT NULL,
is_active BOOLEAN DEFAULT TRUE,
created_at TIMESTAMPTZ DEFAULT NOW()
);
